#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗

[config]
version_check = false

[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/matugen-colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/matugen-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen-colors.conf'
post_hook = 'hyprctl reload &> /dev/null'

[templates.ghostty]
input_path = '~/.config/matugen/templates/matugen-ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.zed]
input_path = '~/.config/matugen/templates/matugen-zed.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.spotify]
input_path = '~/.config/matugen/templates/matugen-spicetify.ini'
output_path = '~/.config/spicetify/Themes/Matugen/color.ini'
post_hook = 'spicetify apply --no-restart'

[templates.firefox-website-colors]
input_path = "~/.config/matugen/templates/matugen-firefox.css"
output_path = "~/.config/matugen/gnome-firefox/matugen-colors.css"

[templates.vesktop]
input_path = '~/.config/matugen/templates/matugen-discord.css'
output_path = '~/.config/vesktop/themes/matugen-discord.css'

[templates.steam]
input_path = '~/.config/matugen/templates/matugen-steam.css'
output_path = '~/.var/app/io.github.Foldex.AdwSteamGtk/config/AdwSteamGtk/custom.css'
post_hook = 'flatpak run io.github.Foldex.AdwSteamGtk -i'

[templates.obs]
input_path = '~/.config/matugen/templates/matugen-obs.obt'
output_path = '~/.var/app/com.obsproject.Studio/config/obs-studio/themes/matugen.obt'
