$image = /home/ziad/Pictures/wallpapers/02. Lucid Aurora.jpg

$background = rgba(191114ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(372e31ff)

$inverse_primary = rgba(884b6aff)

$inverse_surface = rgba(eedfe3ff)

$on_background = rgba(eedfe3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(521d3bff)

$on_primary_container = rgba(ffd8e8ff)

$on_primary_fixed = rgba(380725ff)

$on_primary_fixed_variant = rgba(6d3352ff)

$on_secondary = rgba(402a34ff)

$on_secondary_container = rgba(fdd9e7ff)

$on_secondary_fixed = rgba(29151fff)

$on_secondary_fixed_variant = rgba(59404bff)

$on_surface = rgba(eedfe3ff)

$on_surface_variant = rgba(d4c2c8ff)

$on_tertiary = rgba(4a2811ff)

$on_tertiary_container = rgba(ffdbc8ff)

$on_tertiary_fixed = rgba(301401ff)

$on_tertiary_fixed_variant = rgba(643e25ff)

$outline = rgba(9d8d92ff)

$outline_variant = rgba(504348ff)

$primary = rgba(fdb0d4ff)

$primary_container = rgba(6d3352ff)

$primary_fixed = rgba(ffd8e8ff)

$primary_fixed_dim = rgba(fdb0d4ff)

$scrim = rgba(000000ff)

$secondary = rgba(e0bdcbff)

$secondary_container = rgba(59404bff)

$secondary_fixed = rgba(fdd9e7ff)

$secondary_fixed_dim = rgba(e0bdcbff)

$shadow = rgba(000000ff)

$source_color = rgba(f4bfd6ff)

$surface = rgba(191114ff)

$surface_bright = rgba(40373aff)

$surface_container = rgba(251d21ff)

$surface_container_high = rgba(30282bff)

$surface_container_highest = rgba(3b3236ff)

$surface_container_low = rgba(21191dff)

$surface_container_lowest = rgba(130c0fff)

$surface_dim = rgba(191114ff)

$surface_tint = rgba(fdb0d4ff)

$surface_variant = rgba(504348ff)

$tertiary = rgba(f2bb9aff)

$tertiary_container = rgba(643e25ff)

$tertiary_fixed = rgba(ffdbc8ff)

$tertiary_fixed_dim = rgba(f2bb9aff)

