###################
### MY PROGRAMS ###
###################

$screenshot = hyprshot -o ~/Pictures/Screenshots -m region
$windowScreenshot = hyprshot -o ~/Pictures/Screenshots -m window
$colorPicker = hyprpicker

$powerMenu = pkill -x wlogout || wlogout
$menu = pkill -x rofi || rofi -show drun
$wallpaper = bash ~/.scripts/wallpaper-picker.sh

$fileManager = nautilus
$terminal = ghostty
$browser = firefox


#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpanel

exec-once = awww-daemon
# exec-once = linux-wallpaperengine --screen-root eDP-1

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#############
### BINDS ###
#############

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

##############
### COLORS ###
##############

source = hyprland-colors.conf

general {
    col.active_border = $secondary
    col.inactive_border = $on_secondary
}

###############
### HyprMod ###
###############

source = /home/ziad/.config/hypr/hyprland-gui.conf
