$image = /home/ziad/Pictures/Wallpapers/ice-cream.jpg

$background = rgba(191114ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(372e31ff)

$inverse_primary = rgba(894a67ff)

$inverse_surface = rgba(eedfe2ff)

$on_background = rgba(eedfe2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(531d38ff)

$on_primary_container = rgba(ffd8e6ff)

$on_primary_fixed = rgba(390722ff)

$on_primary_fixed_variant = rgba(6e334fff)

$on_secondary = rgba(412a33ff)

$on_secondary_container = rgba(fed9e6ff)

$on_secondary_fixed = rgba(2a151eff)

$on_secondary_fixed_variant = rgba(593f4aff)

$on_surface = rgba(eedfe2ff)

$on_surface_variant = rgba(d4c2c7ff)

$on_tertiary = rgba(49280fff)

$on_tertiary_container = rgba(ffdcc6ff)

$on_tertiary_fixed = rgba(301400ff)

$on_tertiary_fixed_variant = rgba(633e23ff)

$outline = rgba(9d8c92ff)

$outline_variant = rgba(504348ff)

$primary = rgba(ffb0d0ff)

$primary_container = rgba(6e334fff)

$primary_fixed = rgba(ffd8e6ff)

$primary_fixed_dim = rgba(ffb0d0ff)

$scrim = rgba(000000ff)

$secondary = rgba(e1bdcaff)

$secondary_container = rgba(593f4aff)

$secondary_fixed = rgba(fed9e6ff)

$secondary_fixed_dim = rgba(e1bdcaff)

$shadow = rgba(000000ff)

$source_color = rgba(c392a5ff)

$surface = rgba(191114ff)

$surface_bright = rgba(40373aff)

$surface_container = rgba(261d20ff)

$surface_container_high = rgba(30282bff)

$surface_container_highest = rgba(3c3235ff)

$surface_container_low = rgba(21191cff)

$surface_container_lowest = rgba(130c0fff)

$surface_dim = rgba(191114ff)

$surface_tint = rgba(ffb0d0ff)

$surface_variant = rgba(504348ff)

$tertiary = rgba(f1bb97ff)

$tertiary_container = rgba(633e23ff)

$tertiary_fixed = rgba(ffdcc6ff)

$tertiary_fixed_dim = rgba(f1bb97ff)

