###################
### MY PROGRAMS ###
###################

$screenshot =
$windowScreenshot =
$colorPicker =

$powerMenu = wlogout
$menu = rofi -show drun
$wallpaper =

$fileManager = nautilus
$terminal = ghostty
$browser = firefox

#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = ags run

exec-once = awww-daemon

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#############
### BINDS ###
#############

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

input {
    kb_layout = us,ara
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =
}

##############
### COLORS ###
##############

source = matugen-colors.conf

general {
    col.active_border = $primary
    col.inactive_border = $background
}

###############
### HyprMod ###
###############

source = /home/ziad/.config/hypr/hyprland-gui.conf
