###################
### MY PROGRAMS ###
###################

$terminal = ghostty
$fileManager = nautilus
$menu = pkill -x  rofi || rofi -show drun
$browser = firefox

#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = eww daemon

exec-once = awww-daemon
# exec-once = linux-wallpaperengine --screen-root eDP-1

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# HyprMod managed settings
source = /home/ziad/.config/hypr/hyprland-gui.conf
